project:
  type: book
  output-dir: _site

execute:
  cache: true   ## see https://quarto.org/docs/projects/code-execution.html
  freeze: false 
  echo: false

book:
  title: "Regression without regrets"
  author: "M. Baillie, G. Heinze & M. Huebner"
  date: today  
  chapters:
    - index.qmd  
    - Bact_intro.qmd 
    - Bact_IDA_plan.qmd
    - Bact_missing.qmd
    - Bact_univar.qmd  
    - _00_Bact_univar.qmd ##TODO: merge  
    - Bact_multivar.qmd
    - Bact_suppl.qmd 
    - Pseudo_log_explainer.qmd
    - references.qmd 
    - SessionInfo.qmd 

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    