project:
  type: book
  output-dir: _site

execute:
  cache: true   ## see https://quarto.org/docs/projects/code-execution.html
  freeze: false 
  echo: false

book:
  title: "Regression without regrets"
  author: "M. Baillie, G. Heinze & M. Huebner"
  date: today  
  chapters:
    - index.qmd  ## REMOVE
    - Bact_intro.qmd ## KEEP - MB CHECKED. TODO how to handle a_bact
    - Bact_IDA_plan.qmd ## KEEP - MB CHECKED. TODO: docs for a_data
    - Bact_missing.qmd ## KEEP - MB Checked
    - Bact_univar.qmd ## long running jobs - use freeze (ARDs?). Issue with functions. 
    - _00_Bact_univar.qmd ## long running jobs - use freeze (ARDs?). Issue with functions. 
    - Bact_multivar.qmd ## KEEP
    - Bact_suppl.qmd ## ADD
    - Pseudo_log_explainer.qmd ## ADD
    - references.qmd ## MB Checked
    - SessionInfo.qmd ## MB checked 
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    